name: Deploy Web Wallet

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Check if the workflow was triggered by a tag (production) or a branch (staging)
      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "ðŸ”¥ Using production environment"
            echo "CNAME=wallet.pactus.org" >> $GITHUB_ENV
          else
            echo "ðŸ§ª Using staging environment"
            echo "CNAME=wallet-beta.pactus.org" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Install dependencies for the wallet package
      - name: Install dependencies for wallet
        run: yarn install
        working-directory: ./packages/wallet

      # Build the wallet package
      - name: Build wallet package
        run: yarn build
        working-directory: ./packages/wallet

      # Link the wallet package globally
      - name: Link wallet package globally
        run: yarn link
        working-directory: ./packages/wallet

      # Link the wallet package to the Next.js project
      - name: Link wallet package to Next.js
        run: yarn link @pactus-wallet/wallet
        working-directory: ./apps/web

      # Install dependencies for the Next.js project
      - name: Install dependencies for Next.js
        run: yarn install
        working-directory: ./apps/web

      # Build the Next.js project
      - name: Build Next.js project
        run: yarn build
        working-directory: ./apps/web

      # Deploy the built project
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: web
          publish_dir: ./apps/web/out
          cname: ${{ env.CNAME }}
